AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Cluster for AlertaUTEC Airflow on Fargate'

Parameters:
  ProjectName:
    Type: String
    Default: alerta-utec-airflow
    Description: Project name for resource naming

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ProjectName}-cluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT  # For cost optimization
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
          Base: 1
      ClusterSettings:
        - Name: containerInsights
          Value: disabled  # Disabled for cost savings
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-cluster

  # CloudWatch Log Group for ECS
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${ProjectName}
      RetentionInDays: 7  # Minimal retention for cost savings

Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${ProjectName}-ECSClusterName

  ECSClusterArn:
    Description: ECS Cluster ARN
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub ${ProjectName}-ECSClusterArn

  ECSLogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref ECSLogGroup
    Export:
      Name: !Sub ${ProjectName}-ECSLogGroupName
